### ISSUE TITLE
A curious question from a fellow docker-compose user

### ISSUE THREAD

**Issue by jaypatel512** [julianespinel/stockreader#24]
We have a similar setup as you when [deploying our applications to live](https://github.com/julianespinel/stockreader/wiki/Deploy-to-AWS-using-docker-machine-and-docker-compose). However, I do run into issue when I try to push my code to EC2 instances. The build command for my tomcat server takes forever.

Also, I have to remove all the docker-images and volumes everytime we redeploy, as it maxes out our disk space. Do you know of any performant way of accomplishing that ?

**Comment by julianespinel** [comment]
Hi @jaypatel512 not really, I don't know about the tomcat issue, never happened to me before.
Regarding the cleaning of docker images, volumes, etc, I use this: https://github.com/ZZROTDesign/docker-clean

Hope it helps.
